import Head from "next/head";
import React, { useRef } from "react";
import { Hero } from "../components";
import { Content } from "../components/Content/Content";

export default function Home() {
  // const [selectedItem, setSelectedItem] = React.useState(""); // TODO: Implement this state if want to do an action on clicking card!
  const aboutRef = useRef(null);
  const expRef = useRef(null);
  const projectRef = useRef(null);

  const onClickContent = (title: string) => {
    // setSelectedItem(title);
  };

  return (
    <div>
      <Head>
        <title>Adrian Rivaldy - Frontend Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-[80rem] lg:px-8 mx-auto lg:mt-8 lg:flex min-h-screen">
        <Hero aboutRef={aboutRef} expRef={expRef} projectRef={projectRef} />
        <Content
          onClickContent={onClickContent}
          aboutRef={aboutRef}
          expRef={expRef}
          projectRef={projectRef}
        />
      </main>
    </div>
  );
}
